packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js-pure: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
  prisma: true