use std::fs::File;
use std::io::{Read, Write};
use num_complex::Complex;
use rustfft::{FftPlanner};

fn fftshift_2d<T: Clone>(data: &mut [T], height: usize, width: usize) {
    let half_h = height / 2;
    let half_w = width / 2;
    for r in 0..half_h {
        for c in 0..half_w {
            let i0 = r * width + c;
            let i3 = (r + half_h) * width + (c + half_w);
            data.swap(i0, i3);

            let i1 = r * width + (c + half_w);
            let i2 = (r + half_h) * width + c;
            data.swap(i1, i2);
        }
    }
}

fn fft2d(data: &mut [Complex<f64>], height: usize, width: usize, inverse: bool) {
    let mut planner = FftPlanner::new();
    
    // 1. Row FFTs
    let fft_row = if inverse {
        planner.plan_fft_inverse(width)
    } else {
        planner.plan_fft_forward(width)
    };
    let mut scratch = vec![Complex::new(0.0, 0.0); fft_row.get_inplace_scratch_len()];
    for r in 0..height {
        let row_start = r * width;
        let row_end = row_start + width;
        fft_row.process_with_scratch(&mut data[row_start..row_end], &mut scratch);
    }
    
    // 2. Col FFTs (using transpose)
    let mut transposed = vec![Complex::new(0.0, 0.0); height * width];
    for r in 0..height {
        for c in 0..width {
            transposed[c * height + r] = data[r * width + c];
        }
    }
    
    let fft_col = if inverse {
        planner.plan_fft_inverse(height)
    } else {
        planner.plan_fft_forward(height)
    };
    let mut scratch_col = vec![Complex::new(0.0, 0.0); fft_col.get_inplace_scratch_len()];
    for c in 0..width {
        let col_start = c * height;
        let col_end = col_start + height;
        fft_col.process_with_scratch(&mut transposed[col_start..col_end], &mut scratch_col);
    }
    
    for c in 0..width {
        for r in 0..height {
            data[r * width + c] = transposed[c * height + r];
        }
    }
    
    if inverse {
        let scale = (height * width) as f64;
        for val in data.iter_mut() {
            *val /= scale;
        }
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let resolution = 256;

    // 1. Read complex raw k-space generated by Python (256 * 256 * 2 f64 values)
    let kspace_file_path = "../ai-service/kspace_python.bin";
    let mut file = File::open(kspace_file_path)?;
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer)?;

    let num_elements = buffer.len() / 8;
    assert_eq!(num_elements, resolution * resolution * 2);

    let mut kspace = vec![Complex::new(0.0, 0.0); resolution * resolution];
    for i in 0..(resolution * resolution) {
        let real_bytes = &buffer[(i * 2) * 8..((i * 2) * 8 + 8)];
        let imag_bytes = &buffer[(i * 2 + 1) * 8..((i * 2 + 1) * 8 + 8)];
        
        let re = f64::from_le_bytes(real_bytes.try_into()?);
        let im = f64::from_le_bytes(imag_bytes.try_into()?);
        kspace[i] = Complex::new(re, im);
    }

    // 2. Zero-order phase correction (subtract phase at the peak of 2D k-space)
    let mut peak_val = 0.0;
    let mut peak_phase = 0.0;
    for val in kspace.iter() {
        let mag = val.norm();
        if mag > peak_val {
            peak_val = mag;
            peak_phase = val.arg();
        }
    }
    let correction = Complex::from_polar(1.0, -peak_phase);
    for val in kspace.iter_mut() {
        *val *= correction;
    }

    // 3. Centering & 2D IFFT: input ifftshift, ifft2, output fftshift
    let mut recon_img = kspace.clone();
    fftshift_2d(&mut recon_img, resolution, resolution);
    fft2d(&mut recon_img, resolution, resolution, true); // inverse FFT
    fftshift_2d(&mut recon_img, resolution, resolution);

    // 4. Low-res coil phase alignment (using 24x24 center calibration)
    let cal_size = 24;
    let cal_start = (resolution - cal_size) / 2;
    let mut cal_kspace = vec![Complex::new(0.0, 0.0); resolution * resolution];
    for r in cal_start..(cal_start + cal_size) {
        for col in cal_start..(cal_start + cal_size) {
            let idx = r * resolution + col;
            cal_kspace[idx] = kspace[idx];
        }
    }
    fftshift_2d(&mut cal_kspace, resolution, resolution);
    fft2d(&mut cal_kspace, resolution, resolution, true);
    fftshift_2d(&mut cal_kspace, resolution, resolution);

    for i in 0..(resolution * resolution) {
        let phase = cal_kspace[i].arg();
        recon_img[i] *= Complex::from_polar(1.0, -phase);
    }

    // 5. Magnitude combination (since coils=1, just absolute value of the single coil)
    let mut magnitude_img = vec![0.0; resolution * resolution];
    for i in 0..(resolution * resolution) {
        magnitude_img[i] = recon_img[i].norm();
    }

    // 6. Save reconstructed magnitude to binary file (resolution * resolution f64 values)
    let mut magnitude_bytes = Vec::new();
    for val in magnitude_img.iter() {
        magnitude_bytes.extend_from_slice(&val.to_le_bytes());
    }
    let mut magnitude_file = File::create("rust_recon.bin")?;
    magnitude_file.write_all(&magnitude_bytes)?;

    println!("Success! Rust reconstruction complete.");
    println!("Saved reconstructed magnitude to rust_recon.bin");

    Ok(())
}
